# Generated by Django 6.0.1 on 2026-02-05 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MedicalHistory',
            new_name='MedicalReport',
        ),
    ]
