# Generated by Django 6.0.1 on 2026-02-06 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_alter_medicalreport_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreport',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_report', to='newapp.booking'),
        ),
    ]
